### ISSUE TITLE
ERROR in compilation

### ISSUE THREAD

**Issue by anemartinezlarrinaga2898** [xzhoulab/CoCoNet#1]
Hello, 

I'm trying to instal CoCoNet in R and getting this error: 

```
ERROR: compilation failed for package ‘CoCoNet’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/CoCoNet’
```

I have already loads Rcpp and RcppAmardillo and still not working. 

Any helo? 

Thanks

**Comment by shangll123** [comment]
Hello, 

Thanks for your interest in CoCoNet! I tested the code below

`devtools::install_github('xzhoulab/CoCoNet')`

on different platforms with the same R version (4.1) that you are using, and the package can be successfully installed. The platforms I tested include CentOS7, Ubuntu 18.04.6, and Arch Linux. Would you mind providing more information about which platform (linux/windows/mac) and which compiler you are using, so that we can help to take a deeper look into this installation issue? Also, it might be helpful to update the dependency packages during the installation. 

Best,
Lulu

**Comment by anemartinezlarrinaga2898** [comment]
I solved it! 

I didn't have any compilation instalad, so installing fortran help!
Thank you for the answer!

**Comment by shangll123** [comment]
Great!!! Sure no problem, please don't hesitate to tell me if you have any other questions about the package. 

Best,
Lulu
